package com.android.bookswap.ui

const val MAXLENGTHGREETING = 5
const val MAXLENGTHFIRSTNAME = 100
const val MAXLENGTHLASTNAME = 300
const val MAXLENGTHPHONE = 20
const val MAXLENGTHEMAIL = 320
const val MAXLENGTHMESSAGE = 100000
const val MAXLENGTHISBN = 17
const val MAXLENGTHTITLE = 50
const val MAXLENGTHAUTHOR = 50
const val MAXLENGTHDESCRIPTION = 10000
const val MAXLENGTHRATING = 1
const val MAXLENGTHPHOTO = 500
