name: Build APK

on:
  push:
    branches:
      - main
      - M1
      - M2
      - M3
      - feature/EdenKahane/apkBuild
  workflow_dispatch:

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Load google-services.json and local.properties from the secrets
      - name: Decode secrets
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
        run: |
          echo "$GOOGLE_SERVICES" | base64 --decode > ./app/google-services.json
          echo "$LOCAL_PROPERTIES" | base64 --decode > ./local.properties

      - name: Build Apk
        run: |
          ./gradlew assembleRelease # Build the release version
      - name: Move files
        run: |
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/app-release.apk
          ls -l app/build/outputs/app-release.apk
      - name: Sign App
        id: sign_app
        uses: ilharp/sign-android-release@v1.0.4
        with:
          releaseDir: app/build/outputs
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: apk-signed.apk
          path: $ANDROID_SIGNED_FILE
          if-no-files-found: error
          overwrite: true